workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      android_signing:
        - projectuasppb_keystore
      vars:
        PACKAGE_NAME: "com.example.projectuasppb"
        KEYSTORE_PATH: $FCI_BUILD_DIR/android/app/keystore.jks
    triggering:
      events:
        - push
        - pull_request
      branch:
        include:
          - main
    scripts:
      - name: Set Flutter version
        script: |
          flutter channel stable
          flutter upgrade
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Create .env file from environment variables
        script: |
          # Create .env file only if environment variables are set
          if [ -n "$SUPABASE_URL" ] && [ -n "$SUPABASE_ANON_KEY" ]; then
            cat > .env << EOF
          SUPABASE_URL=$SUPABASE_URL
          SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
          EOF
            echo ".env file created successfully"
            cat .env
          else
            echo "Environment variables not set, using fallback configuration"
          fi
      - name: Build APK
        script: |
          flutter build apk \
            --release \
            --build-number=$BUILD_NUMBER
      - name: Build AAB for Play Store
        script: |
          flutter build appbundle \
            --release \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/apk/release/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - benkoswara655@gmail.com
        notify:
          success: true
          failure: true

  android-debug:
    name: Android Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    triggering:
      events:
        - push
      branch:
        include:
          - develop
    scripts:
      - name: Set Flutter version
        script: |
          flutter channel stable
          flutter upgrade
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Create .env file from environment variables
        script: |
          # Create .env file only if environment variables are set
          if [ -n "$SUPABASE_URL" ] && [ -n "$SUPABASE_ANON_KEY" ]; then
            cat > .env << EOF
          SUPABASE_URL=$SUPABASE_URL
          SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
          EOF
            echo ".env file created successfully"
            cat .env
          else
            echo "Environment variables not set, using fallback configuration"
          fi
      - name: Build Debug APK
        script: |
          flutter build apk \
            --debug \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - benkoswara655@gmail.com
        notify:
          success: true
          failure: true
